"""
Knowledge graph compiler: fuses unpushed git patches + Cursor chat with prior wiki via LLM.

Provider selection is centralized in ``WikiCompiler._call_llm`` so the compile
path can fail soft when every backend is unavailable.
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib import error, request

from cerebro.adapters.cursor_adapter import (
    read_unpushed_patch_text,
)
from cerebro.core.router import get_pending_intents
from cerebro.storage.sqlite_db import resolve_repo_root

_MAX_INPUT_CHARS = 200_000
_MAX_PAYLOAD_CHARS = 24_000
_MAX_PROMPT_CHARS = 24_000
_AUTO_GEN_PATTERNS = (
    "package-lock.json",
    "yarn.lock",
    ".svg",
    ".csv",
    ".min.js",
)


def _print_error(message: str) -> None:
    """Emit a red ``[ERROR]`` line on stderr for operator visibility in hooks and CI."""
    sys.stderr.write(f"\033[31m[ERROR]\033[0m {message}\n")
    sys.stderr.flush()


def _is_autogen_diff_path(path: str) -> bool:
    p = path.strip().lower()
    return (
        p.endswith("/package-lock.json")
        or p.endswith("/yarn.lock")
        or p.endswith(".svg")
        or p.endswith(".csv")
        or p.endswith(".min.js")
        or p in _AUTO_GEN_PATTERNS
    )


def _strip_massive_autogen_diffs(diff_text: str) -> str:
    """
    Remove entire diff blocks for known autogenerated/high-noise files.
    """
    if not diff_text.strip():
        return ""
    lines = diff_text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        if not line.startswith("diff --git "):
            out.append(line)
            i += 1
            continue
        j = i + 1
        while j < n and not lines[j].startswith("diff --git "):
            j += 1
        block = lines[i:j]
        header = block[0].strip()
        m = re.match(r"diff --git a/(.+?) b/(.+)$", header)
        path = ""
        if m:
            path = m.group(2)
        if not _is_autogen_diff_path(path):
            out.extend(block)
        i = j
    return "".join(out).strip()


def truncate_payload(diff_text: str, cursor_chat: str, max_chars: int = _MAX_PAYLOAD_CHARS) -> tuple[str, str]:
    """
    Keep the combined payload under ``max_chars``.

    Strategy:
    1) Strip noisy autogenerated diff blocks.
    2) If still too large, keep the most recent (tail) chat content.
    3) If still too large, hard-cap diff to fit remainder.
    """
    diff = (diff_text or "").strip()
    chat = (cursor_chat or "").strip()
    if len(diff) + len(chat) <= max_chars:
        return diff, chat

    diff = _strip_massive_autogen_diffs(diff)
    if len(diff) + len(chat) <= max_chars:
        return diff, chat

    allowed_chat = max(0, max_chars - len(diff))
    if len(chat) > allowed_chat:
        chat = chat[-allowed_chat:] if allowed_chat else ""
    if len(diff) + len(chat) <= max_chars:
        return diff, chat

    # Final safety if diff alone is too large.
    allowed_diff = max(0, max_chars - len(chat))
    if len(diff) > allowed_diff:
        diff = diff[-allowed_diff:] if allowed_diff else ""
    return diff, chat


@dataclass(slots=True)
class WikiCompiler:
    """
    Merge raw git patches, IDE chat, and ``KNOWLEDGE_GRAPH.md`` into one artifact.

    Attributes:
        out_dir: Directory containing ``KNOWLEDGE_GRAPH.md`` (typically ``.cerebro``).
    """

    out_dir: Path

    _MODEL: str = "llama3"
    _OLLAMA_URL: str = "http://localhost:11434/api/generate"
    _ANTHROPIC_URL: str = "https://api.anthropic.com/v1/messages"
    _OPENAI_URL: str = "https://api.openai.com/v1/chat/completions"
    _GROQ_URL: str = "https://api.groq.com/openai/v1/chat/completions"

    def _existing_wiki_text(self, wiki_path: Path) -> str:
        """Load prior graph text; tolerate missing or unreadable files."""
        if not wiki_path.is_file():
            return ""
        try:
            return wiki_path.read_text(encoding="utf-8").strip()
        except (OSError, UnicodeDecodeError) as exc:
            _print_error(f"Could not read existing wiki: {exc}")
            return ""

    def _build_merge_prompt(
        self, existing_wiki: str, diff_text: str, chat_text: str
    ) -> str:
        instruction = """You are the Permanent Architectural Memory of this codebase. You do not just track the current state; you track the EVOLUTION of the architecture.

You receive raw git diffs (unpushed), IDE chat logs, and an EXISTING_WIKI. Ignore debugging noise, syntax errors, and failed prompts. Prefer durable architectural facts (invariants, contracts, data flows, ownership boundaries) over transient bug chatter.

STRICT OUTPUT RULE: DO NOT engage in conversation. DO NOT say 'What a fascinating piece of code'. START your response immediately with the header '## Project Focus'. If no intents are provided, focus solely on the git diffs. If intents ARE provided, you MUST explicitly document them in an '## Architectural Decisions' section.

STRICT BEHAVIORAL RULES (ADR / neural pathways):

RULE 1 - NO AMNESIA: NEVER delete an old architectural decision. Append new knowledge, do not overwrite.

RULE 2 - THE PIVOT: If the developer pivots or changes a previous decision, you MUST create a `### PIVOT` block. Do not hallucinate examples; use ONLY the provided chat intent.

RULE 3 - THE NEURAL LINK: You must explicitly state WHY the pivot happened based on the chat history. Link the old decision to the new decision so future developers understand the historical context and the exact reasoning for the switch.

RULE 4 - FORMATTING: Maintain a highly structured, scannable Markdown format.

OUTPUT SHAPE (integrate with EXISTING_WIKI; never erase prior decisions):
- Use exact top-level sections: `## Project Focus`, `## Architectural Decisions`, `## File Dictionary`.
- For each pivot, use `### PIVOT` then subsections such as **From**, **To**, **Why (from chat)**, **Neural link** (one short paragraph tying old → new reasoning).
- Use wikilinks or inline cross-references (e.g. `[[ComponentName]]`, `see also: [[Topic]]`) where helpful.
- Truncate git hashes to 7 characters when you cite them.
- No conversational preamble or meta-commentary. Markdown body only.

EXISTING_WIKI (carry forward in full; append and link; do not replace with a blank slate):
"""
        wiki_body = existing_wiki or "_(empty — derive the initial wiki from RAW_GIT_DIFFS and PENDING_ARCHITECTURAL_INTENTS only.)_"
        no_diff = "_(no unpushed patch text resolved — upstream may be missing.)_"
        no_chat = "_(no pending architectural intents were provided.)_"
        scaffold = (
            f"{instruction}\n\n"
            "RAW_GIT_DIFFS (unpushed commits, `git log UP..HEAD -p` style):\n"
            f"{no_diff}\n\n"
            "CRITICAL: PENDING ARCHITECTURAL INTENTS TO BE INTEGRATED:\n"
            f"{no_chat}\n"
        )
        payload_budget = max(0, min(_MAX_PAYLOAD_CHARS, _MAX_PROMPT_CHARS - len(scaffold)))
        diff_block, chat_block = truncate_payload(diff_text, chat_text, payload_budget)
        if len(diff_block) > _MAX_INPUT_CHARS:
            diff_block = diff_block[:_MAX_INPUT_CHARS] + "\n\n[… truncated by Cerebro …]"
        if len(chat_block) > _MAX_INPUT_CHARS:
            chat_block = chat_block[:_MAX_INPUT_CHARS] + "\n\n[… truncated by Cerebro …]"

        payload_len = len(diff_block or no_diff) + len(chat_block or no_chat)
        wiki_budget = max(0, _MAX_PROMPT_CHARS - len(scaffold) - payload_len)
        if len(wiki_body) > wiki_budget:
            wiki_body = wiki_body[-wiki_budget:] if wiki_budget else ""

        prompt = (
            f"{instruction}{wiki_body}\n\n"
            "RAW_GIT_DIFFS (unpushed commits, `git log UP..HEAD -p` style):\n"
            f"{diff_block or no_diff}\n\n"
            "CRITICAL: PENDING ARCHITECTURAL INTENTS TO BE INTEGRATED:\n"
            f"{chat_block or no_chat}\n"
        )
        if len(prompt) > _MAX_PROMPT_CHARS:
            overflow = len(prompt) - _MAX_PROMPT_CHARS
            if overflow > 0 and wiki_body:
                wiki_body = wiki_body[overflow:]
                prompt = (
                    f"{instruction}{wiki_body}\n\n"
                    "RAW_GIT_DIFFS (unpushed commits, `git log UP..HEAD -p` style):\n"
                    f"{diff_block or no_diff}\n\n"
                    "CRITICAL: PENDING ARCHITECTURAL INTENTS TO BE INTEGRATED:\n"
                    f"{chat_block or no_chat}\n"
                )
            if len(prompt) > _MAX_PROMPT_CHARS:
                prompt = prompt[:_MAX_PROMPT_CHARS]
        return prompt

    def _call_anthropic(self, prompt: str) -> str | None:
        api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
        if not api_key:
            return None
        payload = json.dumps(
            {
                "model": "claude-3-5-sonnet-latest",
                "max_tokens": 2000,
                "messages": [{"role": "user", "content": prompt}],
            },
            ensure_ascii=False,
        ).encode("utf-8")
        req = request.Request(
            self._ANTHROPIC_URL,
            data=payload,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                raw = resp.read().decode("utf-8")
        except (error.HTTPError, error.URLError, OSError) as exc:
            _print_error(f"Anthropic request failed: {exc}")
            return None

        try:
            data = json.loads(raw)
            content = data.get("content", [])
            if not isinstance(content, list):
                raise TypeError("content is not a list")
            text_chunks = [
                str(item.get("text", "")).strip()
                for item in content
                if isinstance(item, dict) and item.get("type") == "text"
            ]
            merged = "\n".join(chunk for chunk in text_chunks if chunk).strip()
            if not merged:
                raise ValueError("response did not include text content")
            return merged
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            _print_error(f"Anthropic returned invalid response payload: {exc}")
            return None

    def _call_openai(self, prompt: str) -> str | None:
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not api_key:
            return None
        payload = json.dumps(
            {
                "model": "gpt-4o",
                "messages": [{"role": "user", "content": prompt}],
            },
            ensure_ascii=False,
        ).encode("utf-8")
        req = request.Request(
            self._OPENAI_URL,
            data=payload,
            headers={
                "Authorization": f"Bearer {api_key}",
                "content-type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                raw = resp.read().decode("utf-8")
        except (error.HTTPError, error.URLError, OSError) as exc:
            _print_error(f"OpenAI request failed: {exc}")
            return None

        try:
            data = json.loads(raw)
            choices = data.get("choices", [])
            if not isinstance(choices, list) or not choices:
                raise ValueError("choices list missing or empty")
            first = choices[0]
            if not isinstance(first, dict):
                raise TypeError("first choice is not an object")
            message = first.get("message")
            if not isinstance(message, dict):
                raise TypeError("choice message is not an object")
            content = str(message.get("content", "")).strip()
            if not content:
                raise ValueError("message content is empty")
            return content
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            _print_error(f"OpenAI returned invalid response payload: {exc}")
            return None

    def _call_gemini(self, prompt: str) -> str | None:
        api_key = os.environ.get("GEMINI_API_KEY", "").strip()
        if not api_key:
            return None
        payload = json.dumps(
            {"contents": [{"parts": [{"text": prompt}]}]},
            ensure_ascii=False,
        ).encode("utf-8")
        req = request.Request(
            (
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"gemini-2.5-flash:generateContent?key={api_key}"
            ),
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                raw = resp.read().decode("utf-8")
        except (error.HTTPError, error.URLError, OSError) as exc:
            _print_error(f"Gemini request failed: {exc}")
            return None

        try:
            data = json.loads(raw)
            candidates = data.get("candidates", [])
            if not isinstance(candidates, list) or not candidates:
                raise ValueError("candidates list missing or empty")
            first = candidates[0]
            if not isinstance(first, dict):
                raise TypeError("first candidate is not an object")
            content = first.get("content")
            if not isinstance(content, dict):
                raise TypeError("candidate content is not an object")
            parts = content.get("parts", [])
            if not isinstance(parts, list) or not parts:
                raise ValueError("parts list missing or empty")
            first_part = parts[0]
            if not isinstance(first_part, dict):
                raise TypeError("first part is not an object")
            text = str(first_part.get("text", "")).strip()
            if not text:
                raise ValueError("candidate text is empty")
            return text
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            _print_error(f"Gemini returned invalid response payload: {exc}")
            return None

    def _call_groq(self, prompt: str) -> str | None:
        api_key = os.environ.get("GROQ_API_KEY", "").strip()
        if not api_key:
            return None
        payload = json.dumps(
            {
                "model": "llama3-70b-8192",
                "messages": [{"role": "user", "content": prompt}],
            },
            ensure_ascii=False,
        ).encode("utf-8")
        req = request.Request(
            self._GROQ_URL,
            data=payload,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                raw = resp.read().decode("utf-8")
        except (error.HTTPError, error.URLError, OSError) as exc:
            _print_error(f"Groq request failed: {exc}")
            return None

        try:
            data = json.loads(raw)
            choices = data.get("choices", [])
            if not isinstance(choices, list) or not choices:
                raise ValueError("choices list missing or empty")
            first = choices[0]
            if not isinstance(first, dict):
                raise TypeError("first choice is not an object")
            message = first.get("message")
            if not isinstance(message, dict):
                raise TypeError("choice message is not an object")
            content = str(message.get("content", "")).strip()
            if not content:
                raise ValueError("message content is empty")
            return content
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            _print_error(f"Groq returned invalid response payload: {exc}")
            return None

    def _call_ollama(self, prompt: str) -> str | None:
        payload = json.dumps(
            {"model": self._MODEL, "prompt": prompt, "stream": False},
            ensure_ascii=False,
        ).encode("utf-8")
        req = request.Request(
            self._OLLAMA_URL,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=120) as resp:
                raw = resp.read().decode("utf-8")
        except ConnectionError:
            raise
        except error.URLError as exc:
            if isinstance(exc.reason, ConnectionError):
                raise ConnectionError(str(exc)) from exc
            _print_error(f"Local LLM offline or request failed: {exc}")
            return None
        except error.HTTPError as exc:
            _print_error(f"Local LLM offline or request failed: {exc}")
            return None
        except OSError as exc:
            _print_error(f"Network I/O error talking to Ollama: {exc}")
            return None

        try:
            data = json.loads(raw)
        except json.JSONDecodeError as exc:
            _print_error(f"Ollama returned invalid JSON: {exc}")
            return None

        try:
            return str(data["response"]).strip()
        except (KeyError, TypeError) as exc:
            _print_error(f"Ollama JSON missing 'response' field: {exc}")
            return None

    def _call_llm(self, prompt: str) -> str | None:
        """Dispatch by API key env priority, then Ollama. Silent .env load from cwd."""
        env_path = os.path.join(os.getcwd(), ".env")
        try:
            if os.path.exists(env_path):
                with open(env_path, "r", encoding="utf-8") as env_file:
                    for raw_line in env_file:
                        line = raw_line.strip()
                        if not line or line.startswith("#"):
                            continue
                        key, _, value = line.partition("=")
                        key = key.strip()
                        value = value.strip().strip("\"'")
                        if key:
                            os.environ[key] = value
        except OSError:
            pass

        try:
            if os.environ.get("ANTHROPIC_API_KEY"):
                return self._call_anthropic(prompt)
            if os.environ.get("OPENAI_API_KEY"):
                return self._call_openai(prompt)
            if os.environ.get("GEMINI_API_KEY"):
                return self._call_gemini(prompt)
            if os.environ.get("GROQ_API_KEY"):
                return self._call_groq(prompt)
            try:
                return self._call_ollama(prompt)
            except ConnectionError:
                sys.stderr.write(
                    "[CEREBRO INFO] Memory not compiled. No LLM provider found. "
                    "Set ANTHROPIC_API_KEY, OPENAI_API_KEY, GEMINI_API_KEY, "
                    "GROQ_API_KEY, or ensure Ollama is running.\n"
                )
                sys.stderr.flush()
                return None
        except Exception as exc:
            _print_error(f"LLM routing failed: {exc}")
            return None

    def compile(self) -> dict[str, Any]:
        """
        Fuse unpushed diffs + Cursor chat into ``KNOWLEDGE_GRAPH.md`` under ``out_dir``.

        No-ops when there is no new diff text and no chat. Resolves ``out_dir`` to git root.
        """
        root = resolve_repo_root()
        self.out_dir = (self.out_dir if self.out_dir.is_absolute() else root / self.out_dir).resolve()
        self.out_dir.mkdir(parents=True, exist_ok=True)

        wiki_path = self.out_dir / "KNOWLEDGE_GRAPH.md"
        existing_wiki = self._existing_wiki_text(wiki_path)

        diff_text = read_unpushed_patch_text(root)
        chat_text = get_pending_intents(root)

        if not diff_text.strip() and not chat_text.strip():
            return {
                "status": "noop",
                "out_dir": str(self.out_dir),
                "has_diffs": False,
                "has_chat": False,
            }

        prompt = self._build_merge_prompt(existing_wiki, diff_text, chat_text)
        markdown = self._call_llm(prompt)
        if markdown is None:
            return {
                "status": "llm_unavailable",
                "out_dir": str(self.out_dir),
                "has_diffs": bool(diff_text.strip()),
                "has_chat": bool(chat_text.strip()),
            }

        if not markdown:
            _print_error("LLM returned an empty response; wiki not updated.")
            return {
                "status": "error",
                "out_dir": str(self.out_dir),
                "has_diffs": bool(diff_text.strip()),
                "has_chat": bool(chat_text.strip()),
            }

        try:
            wiki_path.write_text(markdown + "\n", encoding="utf-8")
            queue_path = root / ".cerebro" / "intent_queue.json"
            if queue_path.exists():
                try:
                    queue_path.write_text("[]\n", encoding="utf-8")
                except OSError:
                    pass
        except OSError as exc:
            _print_error(f"Failed to write wiki file: {exc}")
            return {
                "status": "error",
                "out_dir": str(self.out_dir),
                "has_diffs": bool(diff_text.strip()),
                "has_chat": bool(chat_text.strip()),
            }

        return {
            "status": "ok",
            "out_dir": str(self.out_dir),
            "file": str(wiki_path),
            "has_diffs": bool(diff_text.strip()),
            "has_chat": bool(chat_text.strip()),
        }

    @staticmethod
    def _is_quiet() -> bool:
        return bool(os.environ.get("CEREBRO_COMPILE_QUIET", "").strip())
